### ISSUE TITLE
In classDiagram methods: abstract, static and return value are conflicting

### ISSUE THREAD

**Issue by dtyeos** [bpruitt-goddard/vscode-mermaid-syntax-highlight#70]
![image](https://user-images.githubusercontent.com/107921024/174815143-cb4792a4-56fa-403f-bb62-d3e1506ab809.png)

Note that Mermaid Preview is also sometimes in trouble:
![image](https://user-images.githubusercontent.com/107921024/174815217-686b03bc-f488-4915-ab25-1538dd744e86.png)

**Comment by bpruitt-goddard** [comment]
Are those all valid use cases? In [the docs](https://mermaid-js.github.io/mermaid/#/classDiagram?id=visibility) it looks like visibility should be after the method, not the return type.

I think these are **valid** and currently working:
* `+foo(X x)`
* `+staticfoo(X x)$`
* `+abstractfoo(X x)*`

These are valid but need proper highlighting:
* `+abstractstaticfoo(X x)*$`
* `+abstractstaticfoo(X x)$*`

I think the rest are invalid because of either:
* A space between the method and the abstract/static. The docs suggest after the `()` and only show with no space.
* Abstract/static needs to occur after the method, not the return value (eg `+staticbar(X x) retval$`)
